routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

/*
|--------------------------------------------------------------------------
| Web Post Routes
|--------------------------------------------------------------------------
|
*/

// Route::get('/posts', 'PostController');

/*
|--------------------------------------------------------------------------
| Built-in Authentication Routes
|--------------------------------------------------------------------------
|
*/
Auth::routes();
Route::get('login/google', 'Auth\GoogleLoginController@redirectToProvider');

Route::get('login/google/callback', 'Auth\GoogleLoginController@handleProviderCallback');

/*
|--------------------------------------------------------------------------
| Authenticated Only Routes
|--------------------------------------------------------------------------
|
| These routes uses the auth middleware, therefore they are only
| accessible to authenticated users.
|
*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    /*
    |--------------------------------------------------------------------------
    | Profile Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::get('user/{param}', 'ProfileController@index')->name('profile.index');
    Route::put('user/profile/{user}', 'ProfileController@update')->name('profile.update');
    Route::put('user/password/{user}', 'ProfileController@passwordUpdate')->name('password.update');

    /*
    |--------------------------------------------------------------------------
    | Image uploads
    |--------------------------------------------------------------------------
    |
    */
    Route::post('image', 'ImageController@store')->name('image.create');

    /*
    |--------------------------------------------------------------------------
    | PREFIX : admin
    |--------------------------------------------------------------------------
    |
    | These routes are prefixed with 'admin'
    |
    */
    Route::prefix('admin')->group(function () {
        Route::get('/user/spy/back', 'UsersController@spyBack')->name('users.spy.back');
        Route::get('/user/spy/{id}', 'UsersController@spy')->name('users.spy');

        /*
        |--------------------------------------------------------------------------
        | Blog
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/post', 'PostController');

        /*
        |--------------------------------------------------------------------------
        | Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/permissions', 'PermissionsController')->except('update', 'edit');
        Route::post('/permissions/add', 'PermissionsController@add')->name('permissions.add');
        Route::post('/permissions/revoke', 'PermissionsController@revoke')->name('permissions.revoke');

        /*
        |--------------------------------------------------------------------------
        | Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/roles', 'RolesController');

        /*
        |--------------------------------------------------------------------------
        | Users Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::get('/users', 'UsersController@index')->name('users.index');
        Route::post('/user/api/{user}/add', 'UsersController@createUserToken')->name('users.api.add');
        Route::get('/user/api/{usertoken}/delete', 'UsersController@deleteUserToken')->name('users.api.delete');
        Route::get('/users/{id}/add', 'UsersController@add')->name('users.add');
        Route::get('/users/{id}/remove', 'UsersController@remove')->name('users.remove');
    });
});

app/Post.php
<?php

namespace App;

use App\User;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title', 'body'
    ];

    protected $casts = [
        'is_online' => 'boolean',
    ];

    /**
     * Relationship: A post belongs to a user (author).
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope: Get only posts that are online.
     *
     * @param [type] $query
     */
    public function scopeOnline($query)
    {
        return $query->is_online;
    }

    

    /**
     * @return mixed
     */
    public function getFillable()
    {
        return $this->fillable;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Post;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storagpe.
     *
     * @param PostRequest|Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        auth()->user()->publish(

            new Post($request->toArray())

        );

        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Post $post
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('post.form', compact('post'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  Post $post
     *
     * @return \Illuminate\Http\Response
     */
    
    public function edit(Post $post)
    {
        return view('post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Post $post)
    {
        $post->update(request(['title', 'body']));

        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return back();
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container mx-auto leading-normal">

    <header>
        <p class="float-right mt-3">
            <a href="{{ route('post.index') }}" class="bg-transparent hover:bg-grey-lighter text-grey-dark hover:text-grey-darker py-2 px-4 border hover:border-grey rounded-sm  no-underline">Retour</a>
        </p>

        <h1 class="text-black font-bold text-4xl pb-3 mb-6 border-b border-grey-light">Rédaction d'un article</h1>
    </header>


    <form class="w-full" method="POST" action="{{ route('post.store') }}">
        {{ csrf_field() }}


        <div class="mb-6">
            <label class="block text-grey font-bold mb-1" for="blog-title">
                Titre
            </label>
            <div class="w-full block">
                <input class="bg-white appearance-none border-2 border-grey-light hover:border-blue rounded w-full py-2 px-4 text-grey-darker" id="blog-title" type="text" name="title" value="{{ old('title') }}">
            </div>
        </div>

        <div class="mb-6">
            <label class="block text-grey font-bold mb-1" for="blog-content">
                Content
            </label>
            <div class="w-full block">
                <textarea id="blog-content" name="body" cols="30" rows="10" class="bg-white appearance-none border-2 border-grey-light hover:border-blue rounded w-full py-2 px-4 text-grey-darker">{{ old('body') }}</textarea>
            </div>
        </div>

        <button type="submit" class="bg-blue hover:bg-blue-dark text-white py-2 px-4 rounded pull-right no-underline">
            Enregistrer
        </button>
    </form>

</div>

@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container mx-auto leading-normal">

    <header>
        <p class="float-right mt-3">
            <a href="{{ route('post.index') }}" class="bg-transparent hover:bg-grey-lighter text-grey-dark hover:text-grey-darker py-2 px-4 border hover:border-grey rounded-sm  no-underline">Retour</a>
        </p>

        <h1 class="text-black font-bold text-4xl pb-3 mb-6 border-b border-grey-light">Modification de l'article #{{ $post->id }}</h1>
    </header>

    <form class="w-full" method="post" action="{{ route('post.update',  $post->id) }}">
        {{ method_field('PUT') }}
        {{ csrf_field() }}

        <div class="mb-6">
            <label class="block text-grey font-bold mb-1" for="blog-title">
                Titre
            </label>
            <div class="w-full block">
                <input class="bg-white appearance-none border-2 border-grey-light hover:border-blue rounded w-full py-2 px-4 text-grey-darker" id="blog-title" type="text" name="title" value="{{ old('title', $post->title) }}">
            </div>
        </div>

        <div class="mb-6">
            <label class="block text-grey font-bold mb-1" for="blog-content">
                Content
            </label>
            <div class="w-full block">
                <textarea id="blog-content" name="body" cols="30" rows="10" class="bg-white appearance-none border-2 border-grey-light hover:border-blue rounded w-full py-2 px-4 text-grey-darker">{{ old('body', $post->body) }}</textarea>
            </div>
        </div>

        <button type="submit" class="bg-blue hover:bg-blue-dark text-white py-2 px-4 rounded pull-right no-underline">
            Enregistrer
        </button>
    </form>

</div>

@endsection

resources/views/post/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container mx-auto leading-normal">
    <header>

        @can('create-articles')
        <p class="float-right mt-3">
            <a href="{{ route('post.create') }}" class="bg-blue hover:bg-blue-dark text-white py-2 px-4 rounded  no-underline">Rédiger une news</a>
        </p>
        @endcan

        <h1 class="text-black font-bold text-4xl pb-3 mb-6 border-b border-grey-light">Blog</h1>
    </header>

    <div class="flex flex-wrap -mx-2">

    @forelse($posts as $post)

        <div class="w-full md:w-1/2 lg:w-1/2 px-4 mb-8">
            <div class="border border-grey-light bg-white shadow">
                <article class="mb-2 p-3">
                    <h2 class="text-grey-darker text-base mb-2 pull-right">By {{ $post->user->name }} for {{ $post->updated_at->diffForHumans() }}</h2>
                    <h2 class="text-black font-bold text-xl mb-2">{{ $post->title }}</h2>
                    <div class="text-grey-darker text-base">
                        {{ str_limit($post->body, 120) }}
                    </div>
                </article>
                <div class="px-6 py-4 text-right">

                    @can('edit-articles')
                        <a href="{{ route('post.edit', $post->id) }}" class="inline-block bg-transparent hover:bg-grey-lighter text-grey-dark hover:text-grey-darker py-2 px-4 border hover:border-grey rounded-sm no-underline leading-tight">
                            Edit
                        </a>
                    @endcan


                    @can('delete-articles')
                    <form method="post" action="{{ route('post.destroy', $post->id) }}" class="inline-block">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="inline-block bg-transparent hover:bg-red text-red-dark hover:text-white py-2 px-4 border hover:border-red-dark rounded-sm no-underline leading-tight">Delete</button>
                        </form>
                    @endcan

                </div>
            </div>
        </div>

    @empty

        <div class="w-full md:w-1/2 mx-auto bg-blue-light p-2 text-center text-2xl font-serif italic">
            <p>Get to your writing !</p>
        </div>

    @endforelse


    </div>


</div>


@endsection