routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

/*
|--------------------------------------------------------------------------
| Web Post Routes
|--------------------------------------------------------------------------
|
*/

// Route::get('/posts', 'PostController');

/*
|--------------------------------------------------------------------------
| Built-in Authentication Routes
|--------------------------------------------------------------------------
|
*/
Auth::routes();
Route::get('login/google', 'Auth\GoogleLoginController@redirectToProvider');

Route::get('login/google/callback', 'Auth\GoogleLoginController@handleProviderCallback');

/*
|--------------------------------------------------------------------------
| Authenticated Only Routes
|--------------------------------------------------------------------------
|
| These routes uses the auth middleware, therefore they are only
| accessible to authenticated users.
|
*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    /*
    |--------------------------------------------------------------------------
    | Profile Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::get('user/{param}', 'ProfileController@index')->name('profile.index');
    Route::put('user/profile/{user}', 'ProfileController@update')->name('profile.update');
    Route::put('user/password/{user}', 'ProfileController@passwordUpdate')->name('password.update');

    /*
    |--------------------------------------------------------------------------
    | Image uploads
    |--------------------------------------------------------------------------
    |
    */
    Route::post('image', 'ImageController@store')->name('image.create');

    /*
    |--------------------------------------------------------------------------
    | PREFIX : admin
    |--------------------------------------------------------------------------
    |
    | These routes are prefixed with 'admin'
    |
    */
    Route::prefix('admin')->group(function () {
        Route::get('/user/spy/back', 'UsersController@spyBack')->name('users.spy.back');
        Route::get('/user/spy/{id}', 'UsersController@spy')->name('users.spy');

        /*
        |--------------------------------------------------------------------------
        | Blog
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/post', 'PostController');

        /*
        |--------------------------------------------------------------------------
        | Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/permissions', 'PermissionsController')->except('update', 'edit');
        Route::post('/permissions/add', 'PermissionsController@add')->name('permissions.add');
        Route::post('/permissions/revoke', 'PermissionsController@revoke')->name('permissions.revoke');

        /*
        |--------------------------------------------------------------------------
        | Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/roles', 'RolesController');

        /*
        |--------------------------------------------------------------------------
        | Users Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::get('/users', 'UsersController@index')->name('users.index');
        Route::post('/user/api/{user}/add', 'UsersController@createUserToken')->name('users.api.add');
        Route::get('/user/api/{usertoken}/delete', 'UsersController@deleteUserToken')->name('users.api.delete');
        Route::get('/users/{id}/add', 'UsersController@add')->name('users.add');
        Route::get('/users/{id}/remove', 'UsersController@remove')->name('users.remove');
    });
});

app/Http/Controllers/PermissionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PermissionForm;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionsController extends Controller
{
    /**
     * Display Listing ressources
     * @return Redirect
     */
    public function index()
    {
        $permissions = Permission::all();

        return view('permission.index', compact('permissions'));
    }

    /**
     * Create permission
     * @param  PermissionForm $form
     * @return Redirect
     */
    public function store(PermissionForm $form)
    {
        $form->persist();

        return back();
    }


    /**
     * Destroy a permission
     * @param  Permission $permission
     * @return Redirect
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();

        return back();
    }

    /**
     * Add permission to Role
     * @param Role $role
     */
    public function add(Role $role)
    {
        $role::find(request('role'))->givePermissionTo(request('permission'));

        return back();
    }

    /**
     * Revoke a permission
     * @param  Role   $role
     * @return Redirect
     */
    public function revoke(Role $role)
    {
        $role = $role::find(request('role'));

        $permission = Permission::find(request('permission'));

        $role->revokePermissionTo($permission);

        return back();
    }
}

resources/views/permission/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="w-full max-w-lg mx-auto leading-normal">
            <h1 class="text-black font-bold text-4xl mb-6 border-b border-grey-light">Permissions</h1>
    </div>
    <div class="w-full max-w-lg mx-auto leading-normal">
    <form  method="POST" action="{{route('permissions.store')}}" class="mb-4 text-center">
        {{csrf_field()}}
        <input type="text" class="form-group form-inline" name="name">
        <button class="bg-blue text-white p-1 m-1 rounded">Créer</button>
    </form>

    <div class="flex flex-wrap -mx-4">
            @foreach($permissions as $permission)
                <div class="w-full md:w-1/3 lg:w-1/3 px-4 mb-2">
                    <div class="border border-grey-light bg-white shadow">
                        <article class="p-3 text-center">
                            <h2 class="text-black font-bold text-xl mb-2 text-center">{{$permission->name}}</h2>
                            <form method="POST" action="{{ route('permissions.destroy', ['permission' => $permission]) }}" class="mb-4 text-center">
                                {{ method_field('DELETE')}}
                                {{ csrf_field()}}
                                <button class="bg-red text-white p-1 m-1 rounded">Supprimer</button>
                            </form>
                        </article>
                    </div>
                </div>
            @endforeach()
        </div>


    </div>


@endsection