routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

/*
|--------------------------------------------------------------------------
| Web Post Routes
|--------------------------------------------------------------------------
|
*/

// Route::get('/posts', 'PostController');

/*
|--------------------------------------------------------------------------
| Built-in Authentication Routes
|--------------------------------------------------------------------------
|
*/
Auth::routes();
Route::get('login/google', 'Auth\GoogleLoginController@redirectToProvider');

Route::get('login/google/callback', 'Auth\GoogleLoginController@handleProviderCallback');

/*
|--------------------------------------------------------------------------
| Authenticated Only Routes
|--------------------------------------------------------------------------
|
| These routes uses the auth middleware, therefore they are only
| accessible to authenticated users.
|
*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    /*
    |--------------------------------------------------------------------------
    | Profile Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::get('user/{param}', 'ProfileController@index')->name('profile.index');
    Route::put('user/profile/{user}', 'ProfileController@update')->name('profile.update');
    Route::put('user/password/{user}', 'ProfileController@passwordUpdate')->name('password.update');

    /*
    |--------------------------------------------------------------------------
    | Image uploads
    |--------------------------------------------------------------------------
    |
    */
    Route::post('image', 'ImageController@store')->name('image.create');

    /*
    |--------------------------------------------------------------------------
    | PREFIX : admin
    |--------------------------------------------------------------------------
    |
    | These routes are prefixed with 'admin'
    |
    */
    Route::prefix('admin')->group(function () {
        Route::get('/user/spy/back', 'UsersController@spyBack')->name('users.spy.back');
        Route::get('/user/spy/{id}', 'UsersController@spy')->name('users.spy');

        /*
        |--------------------------------------------------------------------------
        | Blog
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/post', 'PostController');

        /*
        |--------------------------------------------------------------------------
        | Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/permissions', 'PermissionsController')->except('update', 'edit');
        Route::post('/permissions/add', 'PermissionsController@add')->name('permissions.add');
        Route::post('/permissions/revoke', 'PermissionsController@revoke')->name('permissions.revoke');

        /*
        |--------------------------------------------------------------------------
        | Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::resource('/roles', 'RolesController');

        /*
        |--------------------------------------------------------------------------
        | Users Permissions
        |--------------------------------------------------------------------------
        |
        */
        Route::get('/users', 'UsersController@index')->name('users.index');
        Route::post('/user/api/{user}/add', 'UsersController@createUserToken')->name('users.api.add');
        Route::get('/user/api/{usertoken}/delete', 'UsersController@deleteUserToken')->name('users.api.delete');
        Route::get('/users/{id}/add', 'UsersController@add')->name('users.add');
        Route::get('/users/{id}/remove', 'UsersController@remove')->name('users.remove');
    });
});

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleForm;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $roles = Role::all();

        return view('roles.index', compact('roles'));
    }

    /**
     * Store a new Role
     * @param  RoleForm $form
     * @return Redirect
     */
    public function store(RoleForm $form)
    {
        $form->persist();

        return back();
    }


    /**
     * Destroy Specified Role
     * @param  Role   $role
     * @return Redirect
     */
    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('roles.index');
    }


    /**
     * Return Permission where not yet into the role
     *
     * @todo  improve this with Queries Builder
     *
     * @param  Role   $role
     * @return Redirect
     */
    public function edit(Role $role)
    {
        $rolePermissions = $role->permissions()->get();
        
        $permissions = Permission::all()->whereNotIn('name', $rolePermissions->pluck('name'))->pluck('name');
        
        return view('roles.edit', compact('rolePermissions', 'permissions', 'role'));
    }
}

resources/views/roles/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container px-4 mx-auto pb-6 pt-2">
    <header>
        @can('create-articles')
            <form method='POST' class="float-right" action="{{route('permissions.add', ['role' => $role])}}">
                {{csrf_field()}}
                <select name="permission">
                    @foreach($permissions as $select)
                        <option value="{{$select}}">{{$select}}</option>
                    @endforeach
                </select>
                <button type="submit" class="bg-blue hover:bg-blue-dark text-white py-2 px-4 rounded  no-underline">Ajouter une permission</button>
            </form>
        @endcan

        <h1 class="text-black font-bold text-4xl pb-3 mb-6 border-b border-grey-light">Attribuer des permissions</h1>
    </header>
    <div class=" max-w-lg mx-auto leading-normal">

        @foreach($rolePermissions as $permission)
            <div class="md:w-1/4 lg:w-1/3 px-4 mb-2">
                <div class="border border-grey-light bg-white shadow">
                    <article class="p-3 text-center">
                        <h2 class="text-black font-bold text-xl mb-2 text-center">{{$permission->name}}</h2>
                        <form method="POST" action="{{ route('permissions.revoke', ['permission' => $permission, 'role' => $role]) }}" class="mb-4 text-center">
                            {{ csrf_field()}}
                            <button class="bg-red-dark text-white p-1 m-1 rounded">Retirer</button>
                        </form>
                    </article>
                </div>
            </div>
        @endforeach()


    </div>


@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="w-full max-w-lg mx-auto leading-normal">
        <h1 class="text-black font-bold text-4xl mb-6 border-b border-grey-light">Roles</h1>
    </div>
    <div class="w-full max-w-lg mx-auto leading-normal">

        <form action="{{route('roles.store')}}" class="mb-4 text-center" method="POST">

            {{csrf_field()}}

            <input type="text" class="form-group form-inline" name="name">

            <button class="bg-blue text-white p-1 m-1 rounded">Créer</button>
        </form>

        <div class="flex flex-wrap -mx-4">
            @foreach($roles as $role)
                <div class="w-full md:w-1/3 lg:w-1/3 px-4 mb-2">
                    <div class="border border-grey-light bg-white shadow">
                        <article class=" d-flex p-2 text-center">
                            <h2 class="text-black font-bold text-xl mb-2 text-center">{{$role->name}}</h2>
                            <form method="POST" action="{{ route('roles.destroy', ['role' => $role]) }}" class="mb-4 text-center">
                                {{ method_field('DELETE')}}
                                {{ csrf_field() }}
                                <button class="bg-red-dark text-white p-1 m-1 rounded">Supprimer</button>
                            </form>
                            <form method="GET" action="{{ route('roles.edit', ['role' => $role]) }}" class="mb-4 text-center">
                                {{ csrf_field() }}
                                <button class="bg-blue text-white p-1 m-1 rounded">Modifier</button>
                            </form>
                        </article>
                    </div>
                </div>
            @endforeach()
        </div>


    </div>


@endsection